remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Model Predictive Control of Noninteracting Active Brownian Particles]
description: |
  Titus Quah, Sho C. Takatori, and James B. Rawlings
  Department of Chemical Engineering, University of California, Santa Barbara
